# Generated by Django 4.0.5 on 2023-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinitial',
            name='edit_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postinitial',
            name='message',
            field=models.CharField(max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='postinitial',
            name='reply_to_msg_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
