# Generated by Django 4.0.5 on 2023-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAnalyzer', '0002_alter_postinitial_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinitial',
            name='date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
