# Generated by Django 4.0.5 on 2023-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAnalyzer', '0003_alter_postinitial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinitial',
            name='edit_date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
